networks:
  spike_network:
    driver: bridge
services:
  prometheus:
    image: prom/prometheus:latest
    ports:
    - 9090:9090
    restart: unless-stopped
    volumes:
    - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
  redis:
    command: redis-server --appendonly yes
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
    - redis_data:/data
  spike-snn-event:
    build:
      context: .
      dockerfile: deploy/docker/Dockerfile.production
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '0.5'
          memory: 1G
    environment:
    - ENVIRONMENT=production
    - LOG_LEVEL=INFO
    - ENABLE_MONITORING=true
    healthcheck:
      interval: 30s
      retries: 3
      test:
      - CMD
      - python
      - -c
      - import sys; sys.exit(0)
      timeout: 10s
    ports:
    - 8080:8080
    restart: unless-stopped
version: '3.8'
volumes:
  redis_data: {}
