apiVersion: v1
kind: Service
metadata:
  labels:
    app: neuromorphic-vision
  name: neuromorphic-vision-service
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: neuromorphic-vision
  type: ClusterIP
