name: Bug Report
description: Report a bug or unexpected behavior
title: "[BUG] "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug in spike-snn-event-vision-kit!
        
        Please fill out the form below with as much detail as possible to help us reproduce and fix the issue.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of the bug
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what you expected...
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Provide step-by-step instructions to reproduce the bug
      placeholder: |
        1. Initialize event camera with...
        2. Load model with...
        3. Run inference on...
        4. Error occurs when...
    validations:
      required: true

  - type: textarea
    id: code-snippet
    attributes:
      label: Minimal Code Example
      description: Provide a minimal code example that reproduces the issue
      render: python
      placeholder: |
        import spike_snn_event as snn
        # Your minimal example here...

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Event Camera Interface
        - SNN Models
        - Training Pipeline
        - Hardware Backends (CUDA/Loihi)
        - ROS2 Integration
        - Data Processing
        - Visualization
        - Documentation
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of spike-snn-event-vision-kit are you using?
      placeholder: e.g., 1.2.3 or latest from main
    validations:
      required: true

  - type: dropdown
    id: python-version
    attributes:
      label: Python Version
      description: What Python version are you using?
      options:
        - "3.8"
        - "3.9"
        - "3.10"
        - "3.11"
        - "3.12"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What OS are you running?
      options:
        - Ubuntu 20.04
        - Ubuntu 22.04
        - Ubuntu 24.04
        - macOS Intel
        - macOS Apple Silicon
        - Windows 10
        - Windows 11
        - Other Linux
    validations:
      required: true

  - type: dropdown
    id: hardware
    attributes:
      label: Hardware Backend
      description: Which hardware backend were you using?
      options:
        - CPU only
        - NVIDIA CUDA
        - Intel Loihi 2
        - BrainChip Akida
        - Not applicable

  - type: textarea
    id: error-logs
    attributes:
      label: Error Logs
      description: Please paste any relevant error messages or stack traces
      render: text
      placeholder: Paste error logs here...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or information that might be helpful
      placeholder: Add any other context about the problem here...

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have provided a minimal code example that reproduces the issue
          required: true
        - label: This issue is related to spike-snn-event-vision-kit (not a dependency)
          required: true