apiVersion: v1
kind: Service
metadata:
  labels:
    app: spike-snn-event-vision
  name: spike-snn-event-vision-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: spike-snn-event-vision
  type: LoadBalancer
