apiVersion: v1
kind: Namespace
metadata:
  name: spike-snn-event
  labels:
    name: spike-snn-event
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spike-snn-inference
  namespace: spike-snn-event
  labels:
    app: spike-snn-inference
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spike-snn-inference
  template:
    metadata:
      labels:
        app: spike-snn-inference
        version: v1
    spec:
      containers:
      - name: spike-snn-inference
        image: spike-snn-event:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 9090
          name: metrics
        env:
        - name: CUDA_VISIBLE_DEVICES
          value: "0"
        - name: LOG_LEVEL
          value: "INFO"
        - name: MODEL_PATH
          value: "/app/models"
        - name: ENABLE_GPU
          value: "true"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
            nvidia.com/gpu: 1
          limits:
            memory: "8Gi"
            cpu: "4000m"
            nvidia.com/gpu: 1
        volumeMounts:
        - name: model-storage
          mountPath: /app/models
        - name: config-volume
          mountPath: /app/config
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
        startupProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 30
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: spike-snn-models
      - name: config-volume
        configMap:
          name: spike-snn-config
      nodeSelector:
        accelerator: nvidia-tesla-t4
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
---
apiVersion: v1
kind: Service
metadata:
  name: spike-snn-inference-service
  namespace: spike-snn-event
  labels:
    app: spike-snn-inference
spec:
  selector:
    app: spike-snn-inference
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spike-snn-models
  namespace: spike-snn-event
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: ssd
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spike-snn-config
  namespace: spike-snn-event
data:
  config.yaml: |
    model:
      name: "SpikingYOLO"
      input_size: [128, 128]
      num_classes: 80
      backend: "cuda"
    
    inference:
      batch_size: 8
      max_queue_size: 100
      timeout: 30.0
      enable_caching: true
    
    scaling:
      min_instances: 1
      max_instances: 10
      cpu_threshold: 70.0
      memory_threshold: 80.0
      queue_threshold: 50
    
    monitoring:
      enable_metrics: true
      metrics_port: 9090
      log_level: "INFO"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spike-snn-ingress
  namespace: spike-snn-event
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  tls:
  - hosts:
    - api.spike-snn.example.com
    secretName: spike-snn-tls
  rules:
  - host: api.spike-snn.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: spike-snn-inference-service
            port:
              number: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: spike-snn-hpa
  namespace: spike-snn-event
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: spike-snn-inference
  minReplicas: 2
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  - type: Pods
    pods:
      metric:
        name: queue_size
      target:
        type: AverageValue
        averageValue: "30"
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 30
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Max