apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spike-snn-event
    version: 1.0.0
  name: spike-snn-event
  namespace: spike-snn-event
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spike-snn-event
  template:
    metadata:
      labels:
        app: spike-snn-event
        version: 1.0.0
    spec:
      containers:
      - env:
        - name: ENVIRONMENT
          value: production
        - name: LOG_LEVEL
          value: INFO
        - name: COMPLIANCE_GDPR
          value: 'true'
        - name: COMPLIANCE_CCPA
          value: 'true'
        - name: I18N_ENABLED
          value: 'true'
        - name: DEFAULT_LANGUAGE
          value: en
        image: spike-snn-event:1.0.0
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        name: spike-snn-event
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          limits:
            cpu: 2000m
            memory: 4Gi
          requests:
            cpu: 500m
            memory: 1Gi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
      securityContext:
        fsGroup: 2000
        runAsNonRoot: true
        runAsUser: 1000
